
CREATE TABLE USERS (
    USER_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME  VARCHAR2(50) NOT NULL,
    LAST_NAME   VARCHAR2(50) NOT NULL,
    EMAIL       VARCHAR2(100) UNIQUE NOT NULL,
    PHONE       VARCHAR2(10),
    DATE_JOINED DATE DEFAULT SYSDATE,
    CONSTRAINT USER_ID PRIMARY KEY ( USER_ID )
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID         NUMBER
        REFERENCES USERS ( USER_ID )
    ON DELETE CASCADE UNIQUE NOT NULL,
    TOTAL_SPENT     NUMBER(10, 2) DEFAULT 0,
    SHIPPING_STREET VARCHAR2(100) NOT NULL,
    SHIPPING_CITY   VARCHAR2(50) NOT NULL,
    SHIPPING_STATE  CHAR(2) NOT NULL,
    SHIPPING_ZIP    VARCHAR2(10) NOT NULL,
    BILLING_STREET  VARCHAR2(100) NOT NULL,
    BILLING_CITY    VARCHAR2(50) NOT NULL,
    BILLING_STATE   CHAR(2) NOT NULL,
    BILLING_ZIP     VARCHAR2(10) NOT NULL,
    CONSTRAINT CUSTOMER_ID PRIMARY KEY ( CUSTOMER_ID )
);

CREATE TABLE SELLERS (
    SELLER_ID   NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID     NUMBER
        REFERENCES USERS ( USER_ID )
    ON DELETE CASCADE UNIQUE NOT NULL,
    STORE_NAME  VARCHAR2(100) NOT NULL,
    RATING      NUMBER(3, 2) DEFAULT 0 CHECK ( RATING BETWEEN 0 AND 5 ),
    PERFORMANCE VARCHAR2(50),
    CONSTRAINT SELLER_ID PRIMARY KEY ( SELLER_ID )
);

CREATE TABLE WAREHOUSE (
    WAREHOUSE_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LOCATION     VARCHAR2(100) UNIQUE NOT NULL,
    SHIPPING_STREET VARCHAR2(100) NOT NULL,
    SHIPPING_CITY   VARCHAR2(50) NOT NULL,
    SHIPPING_STATE  CHAR(2) NOT NULL,
    SHIPPING_ZIP    VARCHAR2(10) NOT NULL,
    BILLING_STREET  VARCHAR2(100) NOT NULL,
    BILLING_CITY    VARCHAR2(50) NOT NULL,
    BILLING_STATE   CHAR(2) NOT NULL,
    BILLING_ZIP     VARCHAR2(10) NOT NULL,
    CONSTRAINT WAREHOUSE_ID PRIMARY KEY ( WAREHOUSE_ID )
);

CREATE TABLE INVENTORY (
    INVENTORY_ID INT GENERATED ALWAYS AS IDENTITY,
    WAREHOUSE_ID REFERENCES WAREHOUSE(WAREHOUSE_ID),
    QTY INT DEFAULT 0 NOT NULL,
    LAST_RESTOCK_DATE DATE,
    REORDER_LEVELS NUMBER(10) CHECK (REORDER_LEVELS >= 0),
    CONSTRAINT INVENTORY_ID PRIMARY KEY ( INVENTORY_ID )
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    INVENTORY_ID   NUMBER
        REFERENCES INVENTORY ( INVENTORY_ID ) ON DELETE CASCADE,
    SELLER_ID      NUMBER
        REFERENCES SELLERS ( SELLER_ID )
    ON DELETE CASCADE NOT NULL,
    SUPPLIER_NAME  VARCHAR2(100),
    NAME           VARCHAR2(100) NOT NULL,
    DESCRIPTION    VARCHAR2(255),
    PRICE          NUMBER(10, 2),
    CATEGORY       VARCHAR2(50),
    QTY               NUMBER(10) DEFAULT 0 CHECK ( QTY >= 0 ),
    LAST_RESTOCK_DATE DATE,
    DATE_ADDED     DATE DEFAULT SYSDATE,
    AVERAGE_RATING NUMBER(3, 2) DEFAULT 0,
    CHECK ( PRICE > 0 ),
    CHECK ( AVERAGE_RATING BETWEEN 0 AND 5 ),
    CONSTRAINT PRODUCT_ID PRIMARY KEY ( PRODUCT_ID )
);

CREATE TABLE ORDERS (
    ORDER_ID                NUMBER GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID             NUMBER
        REFERENCES CUSTOMERS ( CUSTOMER_ID ),
    ORDER_DATE              DATE DEFAULT SYSDATE,
    ORDER_STATUS            VARCHAR2(50),
    ESTIMATED_DELIVERY_DATE DATE,
    TRACKING_NUMBER         VARCHAR2(36) UNIQUE,
    CHECK ( ORDER_STATUS IN ( 'Pending', 'Shipped', 'Delivered', 'Cancelled', 'Returned' ) ),
    CONSTRAINT ORDER_ID PRIMARY KEY ( ORDER_ID )
);

CREATE TABLE ORDERPRODUCT (
    ORDER_PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID       NUMBER
        REFERENCES ORDERS ( ORDER_ID ) ON DELETE CASCADE NOT NULL,
    PRODUCT_ID     NUMBER
        REFERENCES PRODUCTS ( PRODUCT_ID ) ON DELETE CASCADE NOT NULL,
    QTY           NUMBER(5),
    CHECK ( QTY > 0 ),
    CONSTRAINT ORDER_PRODUCT_ID PRIMARY KEY ( ORDER_PRODUCT_ID )
);


CREATE TABLE Payment (
    PaymentID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL,
    CustomerID NUMBER NOT NULL,
    PaymentDate DATE DEFAULT SYSDATE,
    Amount NUMBER(10,2) CHECK (Amount > 0),
    PaymentMethod VARCHAR2(20) CHECK (PaymentMethod IN ('Card','PayPal','GiftCard')),
    PaymentStatus VARCHAR2(20) CHECK (PaymentStatus IN ('Pending','Paid','Refunded')),
    CONSTRAINT fk_payment_order FOREIGN KEY (OrderID)
        REFERENCES Orders(OrderID) ON DELETE CASCADE,
    CONSTRAINT fk_payment_customer FOREIGN KEY (CustomerID)
        REFERENCES Customers(CustomerID) ON DELETE CASCADE
);

CREATE TABLE ORDERRETURN (
    RETURN_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID      NUMBER
        REFERENCES ORDERS ( ORDER_ID ) ON DELETE CASCADE NOT NULL,
    RETURN_DATE   DATE DEFAULT SYSDATE,
    RETURN_REASON VARCHAR2(255),
    RETURN_STATUS VARCHAR2(20),
    REFUND_AMOUNT NUMBER(10, 2),
    CHECK ( RETURN_STATUS IN ( 'Pending', 'Approved', 'Refunded' ) ),
    CHECK ( REFUND_AMOUNT >= 0 ),
    CONSTRAINT RETURN_ID PRIMARY KEY (RETURN_ID)
);



