/**
 * All the create table statements for the database.
 * 
 * This should serve as a reference file. If changes need to be made from this,
 * they should be made using alter table statements, and compiled separately.
 * This prevents you from needing to drop the tables if you need to add a 
 * constraint or something.
 * 
 * This is one way (not preferred, but useful for scripting) to have 
 * the same table for different projects in a database, but have different
 * configurations of that table organized into different files, 
 * based on what project you're working on. 
 * 
 * The preferred method is to have table prefixes. Prefixes allow you a ton 
 * of freedom when working in one giant script, because you can reference 
 * areas of the document by prefix, instead of using a filesystem-based approach.
 * 
 * We're using the filesystem-based approach for collaborative organizational
 * purposes.
 */
-- Order of drops, in case we have to start over:
-- DROP TABLE IF EXISTS PAYMENTS;
-- DROP TABLE IF EXISTS ORDER_PRODUCT;
-- DROP TABLE IF EXISTS ORDER_RETURN;
-- DROP TABLE IF EXISTS ORDERS;
-- DROP TABLE IF EXISTS INVENTORY;
-- DROP TABLE IF EXISTS PRODUCTS;
-- DROP TABLE IF EXISTS WAREHOUSES;
-- DROP TABLE IF EXISTS CUSTOMERS;
-- DROP TABLE IF EXISTS SELLERS;
-- DROP TABLE IF EXISTS USERS; 

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE VARCHAR2(10),
    DATE_JOINED DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER UNIQUE NOT NULL REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    TOTAL_SPENT NUMBER(10, 2) DEFAULT 0,
    SHIPPING_STREET VARCHAR2(100) NOT NULL,
    SHIPPING_CITY VARCHAR2(50) NOT NULL,
    SHIPPING_STATE CHAR(2) NOT NULL,
    SHIPPING_ZIP VARCHAR2(10) NOT NULL,
    BILLING_STREET VARCHAR2(100) NOT NULL,
    BILLING_CITY VARCHAR2(50) NOT NULL,
    BILLING_STATE CHAR(2) NOT NULL,
    BILLING_ZIP VARCHAR2(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS SELLERS (
    SELLER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER UNIQUE NOT NULL REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    STORE_NAME VARCHAR2(100) NOT NULL,
    RATING NUMBER(3, 2) DEFAULT 0 CHECK (
        RATING BETWEEN 0
        AND 5
    ),
    PERFORMANCE VARCHAR2(50)
);

CREATE TABLE IF NOT EXISTS WAREHOUSES (
    WAREHOUSE_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LOCATION VARCHAR2(100) UNIQUE NOT NULL,
    SHIPPING_STREET VARCHAR2(100) NOT NULL,
    SHIPPING_CITY VARCHAR2(50) NOT NULL,
    SHIPPING_STATE CHAR(2) NOT NULL,
    SHIPPING_ZIP VARCHAR2(10) NOT NULL,
    BILLING_STREET VARCHAR2(100) NOT NULL,
    BILLING_CITY VARCHAR2(50) NOT NULL,
    BILLING_STATE CHAR(2) NOT NULL,
    BILLING_ZIP VARCHAR2(10) NOT NULL,
    CONSTRAINT WAREHOUSE_ID PRIMARY KEY (WAREHOUSE_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    SELLER_ID NUMBER NOT NULL REFERENCES SELLERS (SELLER_ID) ON DELETE CASCADE,
    SUPPLIER_NAME VARCHAR2(100),
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    PRICE NUMBER(10, 2) CHECK (PRICE > 0),
    CATEGORY VARCHAR2(50),
    DATE_ADDED DATE DEFAULT SYSDATE,
    AVERAGE_RATING NUMBER(3, 2) DEFAULT 0 CHECK (
        AVERAGE_RATING BETWEEN 0
        AND 5
    ),
    CONSTRAINT PRODUCT_ID PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS INVENTORY (
    INVENTORY_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    WAREHOUSE_ID NUMBER REFERENCES WAREHOUSES (WAREHOUSE_ID) ON DELETE CASCADE,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS (PRODUCT_ID) ON DELETE CASCADE,
    QTY NUMBER DEFAULT 0 NOT NULL,
    LAST_RESTOCK_DATE DATE,
    REORDER_LEVELS NUMBER(10) CHECK (REORDER_LEVELS >= 0),
    CONSTRAINT INVENTORY_ID PRIMARY KEY (INVENTORY_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMERS (CUSTOMER_ID) ON DELETE CASCADE,
    ORDER_DATE DATE DEFAULT SYSDATE,
    ORDER_STATUS VARCHAR2(50) CHECK (
        ORDER_STATUS IN (
            'Pending',
            'Shipped',
            'Delivered',
            'Cancelled',
            'Returned'
        )
    ),
    ESTIMATED_DELIVERY_DATE DATE,
    TRACKING_NUMBER VARCHAR2(36) UNIQUE,
    CONSTRAINT ORDER_ID PRIMARY KEY (ORDER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_PRODUCT (
    ORDER_PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID NUMBER NOT NULL REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
    PRODUCT_ID NUMBER NOT NULL REFERENCES PRODUCTS (PRODUCT_ID) ON DELETE CASCADE,
    QTY NUMBER(5) CHECK (QTY > 0),
    CONSTRAINT ORDER_PRODUCT_ID PRIMARY KEY (ORDER_PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID NUMBER NOT NULL REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
    CUSTOMER_ID NUMBER NOT NULL REFERENCES CUSTOMERS (CUSTOMER_ID) ON DELETE CASCADE,
    PAYMENT_DATE DATE DEFAULT SYSDATE,
    AMOUNT NUMBER(10, 2) CHECK (AMOUNT > 0),
    PAYMENT_METHOD VARCHAR2(20) CHECK (
        PAYMENT_METHOD IN ('Card', 'PayPal', 'GiftCard')
    ),
    PAYMENT_STATUS VARCHAR2(20) CHECK (
        PAYMENT_STATUS IN ('Pending', 'Paid', 'Refunded')
    ),
    CONSTRAINT PAYMENT_ID PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_RETURN (
    RETURN_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID NUMBER NOT NULL REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
    RETURN_DATE DATE DEFAULT SYSDATE,
    RETURN_REASON VARCHAR2(255),
    RETURN_STATUS VARCHAR2(20) CHECK (
        RETURN_STATUS IN ('Pending', 'Approved', 'Refunded')
    ),
    REFUND_AMOUNT NUMBER(10, 2) DEFAULT 0 CHECK (REFUND_AMOUNT >= 0),
    CONSTRAINT RETURN_ID PRIMARY KEY (RETURN_ID)
);